### ISSUE TITLE
Broken support button

### ISSUE THREAD

**Issue by pivulic** [Nosto/nosto-magento2-extension#14]
## Problem
Nothing happens when clicking the support button.

![nosto-m2-broken-support-button](https://cloud.githubusercontent.com/assets/7068697/13982004/c5dcdf72-f0e7-11e5-97f7-118debc06d2d.png)

## Expected Result
Something should happen, maybe https://support.nosto.com/ should be open in a new tab?

## How to recreate
1. Navigate to Nosto in Magento Admin.
2. Switch to the **Recommendations** tab.
3. Scroll down and click the **Support** button.

**Comment by hannunosto** [comment]
This one seems to be an issue in the iframe content. I'll ask someone from our UX team to take a look

**Comment by pivulic** [comment]
:+1:

**Comment by oostman** [comment]
@pivulic we decided to remove the button from the Nosto iFrame. It was referencing an old support solution that we no longer use.
