### ISSUE TITLE
Javascript issue with Nosto disabled

### ISSUE THREAD

**Issue by pivulic** [Nosto/nosto-magento2-extension#16]
## Problem
See http://www.vaimo.com/snaps/pablo.ivulic/nosto-js-issue-m2.png where it fails to load the resource.

## Expected result
The error message should not be thrown, even if Nosto has not yet been configured.

## How to recreate
1. Install Nosto module
2. Don't enable it in Magento Admin
3. Check the javascript console on the frontend

**Comment by hannunosto** [comment]
Fixed - added check that Nosto account is defined before displaying the script tag
